export type SitemapGeneratedEntry = {
  pathname: string;
  lastModified: string;
  priority: number;
  changeFrequency: "monthly";
};

// Generated by scripts/generate-sitemap-entries.mjs
export const sitemapGeneratedEntries: SitemapGeneratedEntry[] = [
  {
    "pathname": "/",
    "lastModified": "2026-03-28T16:18:58.085Z",
    "priority": 1,
    "changeFrequency": "monthly"
  },
  {
    "pathname": "/about",
    "lastModified": "2026-03-28T16:18:58.085Z",
    "priority": 0.7,
    "changeFrequency": "monthly"
  },
  {
    "pathname": "/services",
    "lastModified": "2026-03-28T16:22:55.480Z",
    "priority": 0.8,
    "changeFrequency": "monthly"
  },
  {
    "pathname": "/faqs",
    "lastModified": "2026-03-28T16:22:55.481Z",
    "priority": 0.7,
    "changeFrequency": "monthly"
  },
  {
    "pathname": "/contact",
    "lastModified": "2026-01-13T20:26:58-08:00",
    "priority": 0.7,
    "changeFrequency": "monthly"
  }
];
