export type SitemapGeneratedEntry = {
  pathname: string;
  lastModified: string;
  priority: number;
  changeFrequency: "monthly";
};

// Generated by scripts/generate-sitemap-entries.mjs
export const sitemapGeneratedEntries: SitemapGeneratedEntry[] = [
  {
    pathname: "/",
    lastModified: "2026-06-02T19:09:27.526Z",
    priority: 1,
    changeFrequency: "monthly",
  },
  {
    pathname: "/about",
    lastModified: "2026-06-02T11:53:33-07:00",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    pathname: "/services",
    lastModified: "2026-06-02T11:53:33-07:00",
    priority: 0.8,
    changeFrequency: "monthly",
  },
  {
    pathname: "/faqs",
    lastModified: "2026-06-02T11:53:33-07:00",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    pathname: "/contact",
    lastModified: "2026-06-02T11:53:33-07:00",
    priority: 0.7,
    changeFrequency: "monthly",
  },
];
