export type SitemapGeneratedEntry = {
  pathname: string;
  lastModified: string;
  priority: number;
  changeFrequency: "monthly";
};

// Generated by scripts/generate-sitemap-entries.mjs
export const sitemapGeneratedEntries: SitemapGeneratedEntry[] = [
  {
    "pathname": "/",
    "lastModified": "2026-06-02T18:00:37.573Z",
    "priority": 1,
    "changeFrequency": "monthly"
  },
  {
    "pathname": "/about",
    "lastModified": "2026-06-02T18:00:37.501Z",
    "priority": 0.7,
    "changeFrequency": "monthly"
  },
  {
    "pathname": "/services",
    "lastModified": "2026-06-02T18:00:37.501Z",
    "priority": 0.8,
    "changeFrequency": "monthly"
  },
  {
    "pathname": "/faqs",
    "lastModified": "2026-06-02T18:00:37.501Z",
    "priority": 0.7,
    "changeFrequency": "monthly"
  },
  {
    "pathname": "/contact",
    "lastModified": "2026-06-02T18:00:37.501Z",
    "priority": 0.7,
    "changeFrequency": "monthly"
  }
];
